name: CI for HG text summarization

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://huggingface.co/spaces/mrinoyb2/text_summarization
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://huggingface.co/spaces/mrinoyb2/text_summarization main
